Fixed dockerfile for docker containerization
revaturelabs/ask-backend pull request #65
Opened 2019-12-30 20:49 UTC by RyanMarinoff

Fixed the docker file so to allow containerization of the backend.

2019-12-30 22:39 UTC, AdamRev reviewed
If you want to add an EXPOSE that's fine, but why hardcode the name of the jarfile (with version and snapshot) instead of using the argument?

2020-01-02 16:17 UTC, rlayneorr requested changes
Change back to using ARG

2020-01-02 18:13 UTC, RyanMarinoff commented
Changes are made to allow for use of ARG. Success build and deploy on local system with the following commands:

`docker build --build-arg JAR_FILE=./target/ask-0.0.1-SNAPSHOT.jar .`

Output:

```
...snip...
Step 6/6 : EXPOSE 1337/tcp
 ---> Using cache
 ---> b1faaa9521ca
Successfully built b1faaa9521ca
...snip...
```
`docker container run -p 127.0.0.1:1337:1337/tcp b1faaa9521ca`

Note: replace `b1faaa9521ca` with your successful build ID.

2020-01-02 18:17 UTC, rlayneorr approved these changes

2020-01-02 18:17 UTC, merged