This is all my testing done to the Question package
revaturelabs/ask-backend pull request #68
Opened 2020-01-30 20:21 UTC by DennisY-H

2020-01-30 22:12 UTC, AdamDKing requested changes
Read the README, follow the style guide.

2020-02-03 15:12 UTC, DennisY-H commented
We have updated the styling of the test suites.

2020-02-03 17:27 UTC, DennisY-H reviewed
I believe I have properly stylized the script.

2020-02-03 23:34 UTC, russchristina commented on src/test/java/com/revaturelabs/ask/AskApplicationControllerTests.java
> +    assertTrue(exampleQuesiton.getClass() == exampleQuastion2.getClass());
@DennisY-H have you considered using some sort of looping structure to accomplish the initialization? It seems oddly wasteful to do it this way. Not only that, but you could have created your mock data in one central place and just reused it in each test.

2020-02-04 20:43 UTC, russchristina submitted a review, later dismissed

2020-02-05 01:43 UTC, russchristina approved these changes

2020-02-05 01:44 UTC, merged