Profile feature
revaturelabs/ask-backend pull request #87
Opened 2020-02-14 14:20 UTC by dannyr3

Added Email, Bio, and ProfilePic properties to the User.java Class.  Added UpdateUserInfo Method in UserController to saveOrUpdate ProfilePics. Added to the H2 database User columns to store Email, Bio, and ProfilePic.  Added data entries in the appropriate columns in data.sql.

2020-02-18 15:24 UTC, AdamDKing requested changes
See comments.  We'll discuss how to configure environment for CI/CD once requested changes are made/discussed

2020-02-18 15:24 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/user/UserController.java
> +        throw new ResponseStatusException(HttpStatus.NO_CONTENT, "IOException on File.");
NO_CONTENT is not an error response -- replace it with something appropriate please

2020-02-18 15:24 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/user/UserController.java
> + */
Either uncomment this (if it does something) or delete it

2020-02-18 15:24 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/user/UserService.java
> +  User updateUserInfo(User user);
Doesn't update(User u) already exist?

2020-02-18 15:24 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/user/UserServiceImpl.java
> +  }
why is this here?

2020-02-18 15:24 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/user/UserServiceImpl.java
> +        throw new ImageConflictException("Invalid image");
I'm not sure ImageConflictException is reasonable here.. what's the actual problem that occurs if getBytes() returns null?  We want an Exception that describes that

2020-02-19 18:41 UTC, AdamDKing submitted a review, later dismissed
Looks good except for the endpoint, which should be changed

2020-02-19 18:41 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/question/QuestionController.java
> +  @GetMapping("/{expertId}/response")
This mapping means that hitting the endpoint "/questions/1/response" gets a list of questions produced by expert id 1.  That's not good.  users/1/answeredQuestions or similar would be better.  You could potentially use a query string param

2020-02-19 18:41 UTC, AdamDKing commented on src/main/java/com/revaturelabs/ask/question/QuestionController.java
> +  @GetMapping("/{expertId}/response")
/questions?answeredBy=expertId maybe?

2020-02-25 19:01 UTC, JordanAdkins approved these changes

2020-02-25 19:07 UTC, merged